# Generated by GitHub Copilot
[CmdletBinding()]
param(
    [string]$Root = (Get-Location).Path,
    [string[]]$Targets = @(
        "drift-watch",
        "llm-judge",
        "ragbench",
        "prompt-ops",
        "neuralscope",
        "config-forge",
        "interview-os",
        "mlops-sentinel",
        "agent-tracer",
        "agentic-research-assistant",
        "agentic-ui"
    ),
    [switch]$Json
)

# Generated by GitHub Copilot
function Get-RepoPackageMap {
    <#
    .SYNOPSIS
    Merge dependency fields from a package.json payload.
    #>
    param(
        [Parameter(Mandatory = $true)]
        [pscustomobject]$PackageJson
    )

    $merged = @{}
    foreach ($field in @("dependencies", "devDependencies", "peerDependencies")) {
        if ($PackageJson.PSObject.Properties.Name -contains $field -and $null -ne $PackageJson.$field) {
            foreach ($prop in $PackageJson.$field.PSObject.Properties) {
                $merged[$prop.Name] = $prop.Value
            }
        }
    }

    return $merged
}

# Generated by GitHub Copilot
function Test-RegexInFiles {
    <#
    .SYNOPSIS
    Check whether any file contains a provided regex pattern.
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$FilePaths,
        [Parameter(Mandatory = $true)]
        [string]$Pattern
    )

    foreach ($path in $FilePaths) {
        if (-not (Test-Path -Path $path -PathType Leaf)) {
            continue
        }

        $content = Get-Content -Path $path -Raw -ErrorAction SilentlyContinue
        if ($null -ne $content -and $content -match $Pattern) {
            return $true
        }
    }

    return $false
}

# Generated by GitHub Copilot
function Get-FirstExistingPath {
    <#
    .SYNOPSIS
    Resolve the first existing relative path under a repository root.
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepoPath,
        [Parameter(Mandatory = $true)]
        [string[]]$RelativePaths
    )

    foreach ($relativePath in $RelativePaths) {
        $candidate = Join-Path $RepoPath $relativePath
        if (Test-Path -Path $candidate -PathType Any) {
            return $candidate
        }
    }

    return $null
}

# Generated by GitHub Copilot
function New-CheckStatus {
    <#
    .SYNOPSIS
    Build a normalized check status entry.
    #>
    param(
        [Parameter(Mandatory = $true)]
        [bool]$Pass,
        [Parameter(Mandatory = $true)]
        [string]$Ok,
        [Parameter(Mandatory = $true)]
        [string]$Fail,
        [switch]$NotApplicable
    )

    if ($NotApplicable) {
        return [ordered]@{
            pass = $true
            state = "N/A"
            detail = "not applicable"
        }
    }

    return [ordered]@{
        pass = $Pass
        state = if ($Pass) { "PASS" } else { "FAIL" }
        detail = if ($Pass) { $Ok } else { $Fail }
    }
}

# Generated by GitHub Copilot
function Test-Phase1ContractCase {
    <#
    .SYNOPSIS
    Run a lightweight backend API contract test selector.
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$WorkingDirectory,
        [Parameter(Mandatory = $true)]
        [string]$Selector,
        [Parameter(Mandatory = $true)]
        [string]$SuccessDetail,
        [Parameter(Mandatory = $true)]
        [string]$FailureDetail
    )

    $testFile = Join-Path $WorkingDirectory "tests/test_api.py"
    if (-not (Test-Path -Path $testFile -PathType Leaf)) {
        return New-CheckStatus -Pass $false -Ok $SuccessDetail -Fail "missing tests/test_api.py"
    }

    if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
        return New-CheckStatus -Pass $false -Ok $SuccessDetail -Fail "python executable not found"
    }

    Push-Location $WorkingDirectory
    try {
        python -m pytest tests/test_api.py -k $Selector -q *> $null
        $passed = $LASTEXITCODE -eq 0
    }
    finally {
        Pop-Location
    }

    return New-CheckStatus -Pass $passed -Ok $SuccessDetail -Fail $FailureDetail
}

$rows = @()
$allPass = $true

foreach ($target in $Targets) {
    $repoPath = Join-Path $Root $target
    $exists = Test-Path -Path $repoPath -PathType Container

    if (-not $exists) {
        $rows += [pscustomobject]@{
            App = $target
            BackendEntry = "FAIL"
            RequestId = "FAIL"
            SecurityHeaders = "FAIL"
            Probes = "FAIL"
            ProbeAliases = "FAIL"
            BackendTests = "FAIL"
            Phase1Auth = "FAIL"
            Phase1Error = "FAIL"
            FrontendA11y = "FAIL"
            Overall = "FAIL"
            Notes = "repository not found"
        }
        $allPass = $false
        continue
    }

    $backendMain = Get-FirstExistingPath -RepoPath $repoPath -RelativePaths @(
        "backend/app/main.py",
        "api/main.py"
    )
    $backendMiddleware = Get-FirstExistingPath -RepoPath $repoPath -RelativePaths @(
        "backend/app/middleware.py",
        "api/middleware.py"
    )
    $backendTests = Get-FirstExistingPath -RepoPath $repoPath -RelativePaths @(
        "backend/tests",
        "tests"
    )
    $frontendPackage = Join-Path $repoPath "frontend/package.json"
    $rootPackage = Join-Path $repoPath "package.json"

    $backendExists = $null -ne $backendMain
    $isUiLibrary = $target -eq "agentic-ui"

    $backendEntryCheck = if ($isUiLibrary) {
        New-CheckStatus -Pass $true -Ok "ui library" -Fail "ui library" -NotApplicable
    } else {
        New-CheckStatus -Pass $backendExists -Ok "backend entry found" -Fail "missing backend/app/main.py or api/main.py"
    }

    if ($backendExists) {
        $backendSearchFiles = @()
        if ($null -ne $backendMain) {
            $backendSearchFiles += $backendMain
        }
        if ($null -ne $backendMiddleware) {
            $backendSearchFiles += $backendMiddleware
        }

        $requestIdPresent = Test-RegexInFiles -FilePaths $backendSearchFiles -Pattern "X-Request-ID"
        $securityHeadersPresent = Test-RegexInFiles -FilePaths $backendSearchFiles -Pattern "Content-Security-Policy|SecurityHeadersMiddleware|apply_security_headers|X-Frame-Options"
        $healthPresent = Test-RegexInFiles -FilePaths @($backendMain) -Pattern '/health"|/health'''
        $readyPresent = Test-RegexInFiles -FilePaths @($backendMain) -Pattern '/ready"|/ready'''
        $healthzPresent = Test-RegexInFiles -FilePaths @($backendMain) -Pattern '/healthz"|/healthz'''
        $readyzPresent = Test-RegexInFiles -FilePaths @($backendMain) -Pattern '/readyz"|/readyz'''

        $testWorkingDirectory = if (Test-Path -Path (Join-Path $repoPath "backend/tests") -PathType Container) {
            Join-Path $repoPath "backend"
        } else {
            $repoPath
        }

        $requestIdCheck = New-CheckStatus -Pass $requestIdPresent -Ok "request id propagation found" -Fail "missing request id propagation"
        $securityCheck = New-CheckStatus -Pass $securityHeadersPresent -Ok "security header controls found" -Fail "missing security header controls"
        $probeCheck = New-CheckStatus -Pass ($healthPresent -and $readyPresent) -Ok "health and readiness probes found" -Fail "missing /health or /ready"
        $aliasCheck = New-CheckStatus -Pass ($healthzPresent -and $readyzPresent) -Ok "probe aliases found" -Fail "missing /healthz or /readyz"
        $backendTestsCheck = New-CheckStatus -Pass ($null -ne $backendTests) -Ok "backend tests folder found" -Fail "missing backend tests folder"
        $phase1AuthCheck = Test-Phase1ContractCase -WorkingDirectory $testWorkingDirectory -Selector "phase1_auth_required_contract" -SuccessDetail "phase1 auth contract test passed" -FailureDetail "phase1 auth contract test failed"
        $phase1ErrorCheck = Test-Phase1ContractCase -WorkingDirectory $testWorkingDirectory -Selector "phase1_error_contract_response" -SuccessDetail "phase1 error contract test passed" -FailureDetail "phase1 error contract test failed"
    } else {
        $requestIdCheck = New-CheckStatus -Pass $true -Ok "ui library" -Fail "ui library" -NotApplicable
        $securityCheck = New-CheckStatus -Pass $true -Ok "ui library" -Fail "ui library" -NotApplicable
        $probeCheck = New-CheckStatus -Pass $true -Ok "ui library" -Fail "ui library" -NotApplicable
        $aliasCheck = New-CheckStatus -Pass $true -Ok "ui library" -Fail "ui library" -NotApplicable
        $backendTestsCheck = New-CheckStatus -Pass $true -Ok "ui library" -Fail "ui library" -NotApplicable
        $phase1AuthCheck = New-CheckStatus -Pass $true -Ok "ui library" -Fail "ui library" -NotApplicable
        $phase1ErrorCheck = New-CheckStatus -Pass $true -Ok "ui library" -Fail "ui library" -NotApplicable
    }

    $frontendA11yPass = $false
    $frontendNotes = ""

    if (Test-Path -Path $frontendPackage -PathType Leaf) {
        try {
            $packageJson = Get-Content -Path $frontendPackage -Raw | ConvertFrom-Json
            $deps = Get-RepoPackageMap -PackageJson $packageJson
            $hasA11y = $deps.ContainsKey("eslint-plugin-jsx-a11y")
            $hasTestingLibrary = $deps.ContainsKey("@testing-library/react")
            $frontendA11yPass = $hasA11y -and $hasTestingLibrary
            $frontendNotes = if ($frontendA11yPass) {
                "a11y + testing library present"
            } else {
                "missing eslint-plugin-jsx-a11y or @testing-library/react"
            }
        } catch {
            $frontendNotes = "invalid frontend package.json"
        }
    } elseif (Test-Path -Path $rootPackage -PathType Leaf) {
        try {
            $packageJson = Get-Content -Path $rootPackage -Raw | ConvertFrom-Json
            $deps = Get-RepoPackageMap -PackageJson $packageJson
            $hasStorybookA11y = $deps.ContainsKey("@storybook/addon-a11y")
            $hasTestingLibrary = $deps.ContainsKey("@testing-library/react")
            $frontendA11yPass = $hasStorybookA11y -and $hasTestingLibrary
            $frontendNotes = if ($frontendA11yPass) {
                "storybook a11y + testing library present"
            } else {
                "missing @storybook/addon-a11y or @testing-library/react"
            }
        } catch {
            $frontendNotes = "invalid package.json"
        }
    } else {
        $frontendNotes = "frontend package.json not found"
    }

    $frontendCheck = New-CheckStatus -Pass $frontendA11yPass -Ok "frontend a11y baseline found" -Fail $frontendNotes

    $checks = @(
        $backendEntryCheck,
        $requestIdCheck,
        $securityCheck,
        $probeCheck,
        $aliasCheck,
        $backendTestsCheck,
        $phase1AuthCheck,
        $phase1ErrorCheck,
        $frontendCheck
    )

    $repoPass = ($checks | Where-Object { -not $_.pass }).Count -eq 0
    if (-not $repoPass) {
        $allPass = $false
    }

    $noteItems = @()
    foreach ($check in $checks) {
        if (-not $check.pass -and $check.state -ne "N/A") {
            $noteItems += $check.detail
        }
    }

    $rows += [pscustomobject]@{
        App = $target
        BackendEntry = $backendEntryCheck.state
        RequestId = $requestIdCheck.state
        SecurityHeaders = $securityCheck.state
        Probes = $probeCheck.state
        ProbeAliases = $aliasCheck.state
        BackendTests = $backendTestsCheck.state
        Phase1Auth = $phase1AuthCheck.state
        Phase1Error = $phase1ErrorCheck.state
        FrontendA11y = $frontendCheck.state
        Overall = if ($repoPass) { "PASS" } else { "FAIL" }
        Notes = if ($noteItems.Count -gt 0) { $noteItems -join "; " } else { "all checks passed" }
    }
}

$rows | Format-Table -AutoSize

if ($Json) {
    $jsonPath = Join-Path $Root "phase0-production-gate-report.json"
    $rows | ConvertTo-Json -Depth 5 | Set-Content -Path $jsonPath -Encoding UTF8
    Write-Host "\nSaved JSON report to $jsonPath"
}

if (-not $allPass) {
    exit 1
}
