# Generated by GitHub Copilot
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$env:CI = "true"

$targets = @(
    @{ name = "drift-watch"; path = "c:/github_repos/drift-watch/frontend"; mode = "app" },
    @{ name = "llm-judge"; path = "c:/github_repos/llm-judge/frontend"; mode = "app" },
    @{ name = "ragbench"; path = "c:/github_repos/ragbench/frontend"; mode = "app" },
    @{ name = "prompt-ops"; path = "c:/github_repos/prompt-ops/frontend"; mode = "app" },
    @{ name = "neuralscope"; path = "c:/github_repos/neuralscope/frontend"; mode = "app" },
    @{ name = "config-forge"; path = "c:/github_repos/config-forge/frontend"; mode = "app" },
    @{ name = "interview-os"; path = "c:/github_repos/interview-os/frontend"; mode = "app" },
    @{ name = "mlops-sentinel"; path = "c:/github_repos/mlops-sentinel/frontend"; mode = "app" },
    @{ name = "agentic-ui"; path = "c:/github_repos/agentic-ui"; mode = "lib" }
)

$report = @()

foreach ($target in $targets) {
    $row = [ordered]@{
        repo = $target.name
        install = "not-run"
        lint = "not-run"
        test = "not-run"
    }

    if (-not (Test-Path $target.path)) {
        $row.install = "missing-path"
        $row.lint = "missing-path"
        $row.test = "missing-path"
        $report += [pscustomobject]$row
        continue
    }

    Push-Location $target.path
    try {
        Write-Host "`n=== $($target.name): npm install ==="
        npm install
        $row.install = if ($LASTEXITCODE -eq 0) { "pass" } else { "fail" }
        if ($row.install -ne "pass") {
            $report += [pscustomobject]$row
            continue
        }

        Write-Host "=== $($target.name): npm run lint ==="
        npm run lint
        $row.lint = if ($LASTEXITCODE -eq 0) { "pass" } else { "fail" }
        if ($row.lint -ne "pass") {
            $report += [pscustomobject]$row
            continue
        }

        Write-Host "=== $($target.name): tests ==="
        if ($target.mode -eq "lib") {
            npm run test -- --run --passWithNoTests
        }
        else {
            npx vitest run --pool forks --reporter basic
        }
        $row.test = if ($LASTEXITCODE -eq 0) { "pass" } else { "fail" }

        $report += [pscustomobject]$row
    }
    finally {
        Pop-Location
    }
}

$reportPath = "c:/github_repos/frontend-validation-report.json"
$report | ConvertTo-Json -Depth 5 | Set-Content -Path $reportPath -Encoding UTF8

$report | Format-Table -AutoSize
Write-Host "Saved $reportPath"

$failed = $report | Where-Object {
    $_.install -ne "pass" -or $_.lint -ne "pass" -or $_.test -ne "pass"
}
if ($failed.Count -gt 0) {
    exit 1
}
